### PR TITLE
Revamp unified search GraphQL query schema etc

### PR DESCRIPTION
**Pull request by karisal-anders**
**NOTE**: `events-helsinki-monorepo` will need changes in a separate PR to accomodate for the GraphQL query changes!

### refactor: move arg with default value to getSuggestions's args' end

SonarCloud rule "Function parameters with default values should be last"
 - https://rules.sonarsource.com/typescript/RSPEC-1788/

refs US-115

### refactor: use `a || b` instead of `a ? a : b` to remove code smell

SonarCloud rule "Ternary operator should not be used instead of simpler
alternatives":
 - https://rules.sonarsource.com/typescript/RSPEC-6644/

refs US-115

### fix(dockerfile): use double quotes around $YARN_VERSION

SonarCloud rule "Double quote to prevent globbing and word splitting":
 - https://rules.sonarsource.com/docker/RSPEC-6570/

refs US-115

### refactor(dockerfile): use uppercase AS in Dockerfile in FROM clauses

SonarCloud rule "Instructions should be upper case":
 - https://rules.sonarsource.com/docker/RSPEC-6476/

refs US-115

### refactor: refactor Accessibility.fix_unknown_and_zero_shortcomings

Deferred refactorings from PR https://github.com/City-of-Helsinki/unified-search/pull/107
are contained in this commit.

refs US-115

### refactor(graphql): add consts & types for languages and indices

Deferred refactorings related to PR https://github.com/City-of-Helsinki/unified-search/pull/108
are included in this commit

refs US-115

### refactor(graphql): separate orderBy* arg validation, type orderBy* args

Deferred refactorings related to PR https://github.com/City-of-Helsinki/unified-search/pull/108
are included in this commit

refs US-115

### feat(graphql)!: rename orderedByAccessibilityShortcoming field

add:
 - documentation for accessibilityShortcomingFor

BREAKING CHANGES:

rename:
 - orderedByAccessibilityShortcoming -> accessibilityShortcomingFor

refs US-115

### fix(graphql)!: remove unsupported before & last arguments

also clean up schema comments

BREAKING CHANGES:

as "before" and "last" arguments are not supported, just remove them
completely

refs US-115

### feat(graphql)!: rename graphql query argument "q" to "text"

BREAKING CHANGES: rename graphql query argument "q" to "text"

refs US-115

### fix(importers): remove duplicated ontology word importer

there were two ontology word importers:
 - ontology_word.py
 - ontology_words.py
and their only difference was the name of the importer.

because ontology_word.py importer is being but ontology_words.py is not,
remove ontology_words.py as duplicate code

refs US-115

### fix(graphql)!: remove deprecated administrativeDivisionId argument

BREAKING CHANGES: remove deprecated administrativeDivisionId argument

refs US-115

### feat(graphql)!: unify ontologyWordId query args to ontologyWordIdOrSets

add:
 - ontologyWordIdOrSets query argument
   - a list of lists of ontology word IDs, supports and arbitrary amount
	 of different ontology word ID sets

BREAKING CHANGES:

remove:
 - ontologyWordIds query argument

refs US-115

### feat(graphql)!: unify ontologyTreeId query args to ontologyTreeIdOrSets

add:
 - ontologyTreeIdOrSets query argument
   - a list of lists of ontology tree IDs, supports an arbitrary amount
	 of different ontology tree ID sets

BREAKING CHANGES:

remove:
 - ontologyTreeIds query argument
 - ontologyTreeIdsOrSet2 query argument

refs US-115

### fix(graphql)!: remove deprecated ontologyTreeId argument

BREAKING CHANGES: remove deprecated ontologyTreeId argument

refs US-115

## Tickets

[US-115](https://helsinkisolutionoffice.atlassian.net/browse/US-115)

## Related PRs

- [PR #107](https://github.com/City-of-Helsinki/unified-search/pull/107)
  - https://github.com/City-of-Helsinki/unified-search/pull/107#discussion_r1351702790
- [PR #108](https://github.com/City-of-Helsinki/unified-search/pull/108)
  - https://github.com/City-of-Helsinki/unified-search/pull/108#discussion_r1351674389
  - https://github.com/City-of-Helsinki/unified-search/pull/108#discussion_r1351683060
  - https://github.com/City-of-Helsinki/unified-search/pull/108#discussion_r1351687142

[US-115]: https://helsinkisolutionoffice.atlassian.net/browse/US-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr114.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
[Changed] to using ontologyTreeIdOrSets and ontologyWordIdOrSets

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
