### PR TITLE
cronjob not fail if data import fails

### PR DESCRIPTION
**Pull request by terovirtanen**
[US-101](https://helsinkisolutionoffice.atlassian.net/browse/US-101)

[US-101]: https://helsinkisolutionoffice.atlassian.net/browse/US-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr90.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
