### PR TITLE
US-79 & US-82 & US-84 | Misc enhancements

### PR DESCRIPTION
**Pull request by tuomas777**
Miscellaneous mostly production readiness related improvements.

### CODE REVIEW

**Review by nikomakela — APPROVED** [review]
Looks good to me. The data is imported in batch of hundreds which is a good thing. 👍  Could not test sentry yet, because I don't have an access there.

**Comment by nikomakela** [comment]
Not sure if the sentry is ready and waiting yet. I think we could wait for it until we merge this?

**Review by charn — APPROVED** [review]
LGTM! :+1: :shipit:

**Comment by nikomakela** [comment]
Sentry dsn set to secrets. Ready to ship! 🚀

**Pull request merged**
