### PR TITLE
chore: upgrade to Python 3.9

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-578

Install a new virtual env:
```
pyenv virtualenv 3.9 unified-search-39
pyenv activate unified-search-39
pip install pip-tools
```

Upgrade the `sources` dependencies:
```
pip-compile --upgrade requirements-dev.in
pip-compile --upgrade requirements.in
pip-compile --upgrade requirements-prod.in
pip-sync requirements.txt requirements-dev.txt
```

Upgrade the `test` dependencies:
```
pip-compile --upgrade requirements.in
pip-sync requirements.txt
```

Upgrade the `appbase` image in the DockerFile. 
Build and run a new docker container with 
`docker compose up --build`.

Run `black .` and `isort .` to format the code.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr135.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
@nikomakela Something going on with unified-search-sources-review
image

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr135.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr135.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr135.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr135.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by jakezu — COMMENTED** [review]
Looks good for me. There were that discussion about using UBI image, but as there is that ticket about it, so it might be the clearest to handle it later.

And if to want add (somewhere) below tips, how to get containers running in Ubuntu, there those are.

**Fixing Docker memory issues which might occur when trying to build US containers in for example Debian based Linux distribution.**

A. If you see this warning: "Noswaplimitsupport", when running the below command or by via Docker container logs, follow steps 1-3 to fix it.
$ sudo docker info

1. Add following line into: /etc/default/grub
GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"

2. Save and close the file. Then update the GRUB:
$ sudo update-grub

3. Confirm that changes have taken effect after reboot:
$ sudo dockerinfo 


B. If you see below warning, follow step 1 to fix it.
"max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]"

1. Add following line into: /etc/sysctl.conf
vm.max_map_count=262144

**Review by jakezu — APPROVED** [review]

**Pull request merged**
