### PR TITLE
Refactor the getQueryResult by splitting it into multiple files and functions

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-578

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr130.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr130.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Unified search graphql branch is deployed to platta: https://kuva-unified-search-pr130.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by karisal-anders — APPROVED** [review]
As a possible improvement `type getQueryResultsProps` could be capitalized i.e. `type GetQueryResultsProps` for consistency & to make it apparent that it is a type

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr130.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
