### PR TITLE
fix: fix broken LinkedEvents URLs in review and testing environments

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix: fix broken LinkedEvents URLs in review and testing environments

left the commented out URLs for LinkedEvents test environment in
the pipeline files if there's a need to test against the test
environment, alternatively they could be removed completely for clarity

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr111.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Review by nikomakela — APPROVED** [review]
The dev url should never be used, so that could even be totally removed, not just commented out.

**Comment by karisal-anders** [comment]
Changed the commented out dev LinkedEvents URL to test LinkedEvents URL and changed the commit message to reflect the change.

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr111.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
