### PR TITLE
build: test and review environments events url to linked events staging

### PR DESCRIPTION
**Pull request by terovirtanen**
[DEVOPS-543](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-543)

[DEVOPS-543]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Unified search sources branch is deployed to platta: https://kuva-unified-search-sources-pr91.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]
If it has always had that start=today parameter, then it's okay.

**Review by jannetalvio — APPROVED** [review]
Looks good.

**Comment by terovirtanen** [comment]
> If it has always had that start=today parameter, then it's okay.

Yes it is. I copied default url from code and changed base linked events address.

**Pull request merged**
